# Multi-Label ABSA Configuration
# ========================================================================
# For multi-label approach (all 11 aspects predicted simultaneously)
# Model: ViSoBERT with multi-label classification head
# Method: Focal Loss + Contrastive Learning (SOTA 2024)
# Expected: 96.0-96.5% F1
# ========================================================================

paths:
  data_dir: "multi_label/data"
  train_file: "multi_label/data/train_multilabel_balanced.csv"  # Balanced data (15,921 samples)
  validation_file: "multi_label/data/validation_multilabel.csv"
  test_file: "multi_label/data/test_multilabel.csv"
  output_dir: "multi_label/models/multilabel_focal_contrastive"
  evaluation_report: "multi_label/results/evaluation_report_multi.txt"
  predictions_file: "multi_label/results/test_predictions_multi.csv"

model:
  name: "5CD-AI/Vietnamese-Sentiment-visobert"
  num_labels: 33  # 11 aspects × 3 sentiments = 33 outputs
  num_aspects: 11
  num_sentiments: 3
  max_length: 256
  
  # Model architecture
  hidden_size: 512      # Dense layer
  projection_dim: 256   # Contrastive learning projection
  dropout: 0.3

valid_aspects:
  - Battery
  - Camera
  - Performance
  - Display
  - Design
  - Packaging
  - Price
  - Shop_Service
  - Shipping
  - General
  - Others

sentiment_labels:
  positive: 0
  negative: 1
  neutral: 2

training:
  # Batch size for multi-label (larger samples)
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 2  # Effective batch = 64
  # per_device_train_batch_size: 16
  # per_device_eval_batch_size: 32
  # gradient_accumulation_steps: 4  
  # Optimizer settings
  optim: "adamw_bnb_8bit"
  learning_rate: 2.0e-5
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8
  max_grad_norm: 1.0
  
  # Learning rate scheduler
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.06
  
  # Training duration
  num_train_epochs: 15  # More epochs for contrastive learning
  
  # Mixed precision (RTX 3070 Ampere)
  fp16: true
  fp16_opt_level: "O2"
  fp16_full_eval: false
  tf32: true
  
  # DataLoader settings
  dataloader_num_workers: 2  # Reduced for larger batches
  dataloader_pin_memory: true
  dataloader_prefetch_factor: 4
  dataloader_persistent_workers: true
  
  # Memory optimization
  gradient_checkpointing: false
  auto_find_batch_size: false
  group_by_length: false
  
  # Evaluation & checkpointing
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 5
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1"
  greater_is_better: true
  
  # Early stopping
  early_stopping_patience: 5
  early_stopping_threshold: 0.001
  
  # Logging
  logging_strategy: "steps"
  logging_steps: 50
  logging_first_step: true
  report_to: []
  
  # Reproducibility
  seed: 42
  data_seed: 42
  
  # Misc
  disable_tqdm: false
  prediction_loss_only: false
  remove_unused_columns: true
  label_names: ["labels"]
  include_inputs_for_metrics: false

general:
  seed: 42
  device: "auto"
  log_level: "info"

# Multi-label specific settings
multi_label:
  # Loss function combination
  focal_weight: 1        # 95% focus on classification
  contrastive_weight: 0   # 5% focus on representations
  
  # Focal Loss settings
  use_focal_loss: true      # Enable Focal Loss
  focal_gamma: 2.0          # Focusing parameter (higher = more focus on hard examples)
  focal_alpha: "auto"       # Auto class weights from data
  
  # Contrastive Learning settings
  use_contrastive: true     # Enable Contrastive Learning
  contrastive_temperature: 0.1  # Temperature for softmax (0.07-0.15)
  contrastive_base_weight: 0.1  # Base weight for soft similarity
  contrastive_type: "improved"  # "improved" = soft weighting, no threshold
  
  # Data augmentation
  use_balanced_data: true   # Use balanced oversampled data
  balance_method: "aspect_wise"  # Per-aspect balancing
  
  # Inference settings
  batch_prediction: true    # Predict all 11 aspects in one pass
  use_class_weights: true   # Apply class weights in loss
